### ISSUE TITLE
Division by zero possible

### ISSUE THREAD

**Issue by wallbeach** [AreaWorld/ethereum-contracts#2]
**Division by zero possible**

In function onERC721Received:

uint256 a = uint256(0) / uint256(0);

**Comment by fulldecent** [comment]
Thank you for sharing.

You are referring to this line:

https://github.com/AreaWorld/ethereum-contracts/blob/4eb55b7a7f81f63caf54b6ee177ad5b017f762e2/contracts/Mocks/ERC721ReceiverMock.sol#L59

This is part of the test mock [which is excluded form the bug bounty](https://github.com/AreaWorld/ethereum-contracts/blob/main/BUG-BOUNTY.md#scope-of-this-bounty-program). But still I'd like to explain it to you.

The divide by zero is intended functionality. The test mock is used during testing (i.e. it is not deployed as part of the production contract) and it is used to see what happens if a token receiver performs a divide-by-zero when it is receiving a token.

With ERC-721, there is a `safeTransferFrom` function for sending tokens and this allows code to run in the recipient contract. Since we don't have control of all possible recipients of tokens, we do test several kinds of receiving scenarios.
