### ISSUE TITLE
onlyOwner in Ownable.sol

### ISSUE THREAD

**Issue by wallbeach** [AreaWorld/ethereum-contracts#3]
I think the line         
_;
is not necessary

**Comment by fulldecent** [comment]
Thank you for sharing.

You are referring to this line:

https://github.com/AreaWorld/ethereum-contracts/blob/4eb55b7a7f81f63caf54b6ee177ad5b017f762e2/contracts/Vendor/openzeppelin-contracts-3dadd40034961d5ca75fa209a4188b01d7129501/access/Ownable.sol#L43

This is part of code copied from OpenZeppelin Contracts and is in scope for the bounty program because you are reviewing code functionality and not typos/whitespace ([typos and whitespace for copied vendor code is out-of-scope](https://github.com/AreaWorld/ethereum-contracts/blob/main/BUG-BOUNTY.md#sensitivity)).

The line `_;` is intended functionality. This is part of a function "modifier". Please see the relevant documentation from Solidity: https://docs.soliditylang.org/en/v0.8.9/contracts.html?highlight=modifier#function-modifiers

By including the line `_;` a modifier is able to perform checks and also execute the underlying function that is modified.
