### ISSUE TITLE
`AreaNFT.spit` does not call `onERC721Received` when recipient of its `Transfer` events is a contract.

### ISSUE THREAD

**Issue by markegli** [AreaWorld/ethereum-contracts#5]
This can leave the recipient contract unaware of the new children, rendering them untransferable. An easy solution would be for `split` to somehow call `_checkOnERC721Received`, either directly, via`_safeMint`, or by some other means.

Unrelated to issue #1 as this is a problem regardless of if the recipient is the original owner or the message sender.

**Comment by fulldecent** [comment]
Thank you for sharing. First, this issue is indeed separate from #1.

# Identification

You are referring to these lines of code:

1. https://github.com/AreaWorld/ethereum-contracts/blob/4eb55b7a7f81f63caf54b6ee177ad5b017f762e2/contracts/AreaNFT.sol#L55
2. https://github.com/AreaWorld/ethereum-contracts/blob/4eb55b7a7f81f63caf54b6ee177ad5b017f762e2/contracts/AreaNFT.sol#L63

where a token is effectively minted but the recipient does not receive a call to `onERC721Received`.

# References

## Is this disallowed?

[The ERC-721 standard](https://eips.ethereum.org/EIPS/eip-721) specifically disclaims any specification of minting functionality:

> Creating of NFTs (“minting”) and destruction [of] NFTs (“burning”) is not included in the specification.

Therefore, `AreaNFT` does not violate the ERC-721 standard on this accord.

See below a note about another reference in the standard.

## Is this weird/confusing/uncustomary?

But our level of sensitivity here [includes even "Inconsistent usage of whitespace"](https://github.com/AreaWorld/ethereum-contracts/blob/main/BUG-BOUNTY.md#sensitivity). So we don't need to argue that the behavior is disallowed, we merely need to show it is confusing to be a valid bug report.

Here are two (most?) notable implementations of ERC-721:

1. https://github.com/0xcert/ethereum-erc721/blob/master/src/contracts/tokens/nf-token.sol#L326 (official, reference implementation)
2. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol (popular)

Both of them include mint-without-calling-`onERC721Received` functionality as first-class features.

This means AreaNFT is doing something that many other people are doing and which is well-known.

The `split` function may produce up to 400 NFTs so of course using `safeMint` here is not possible (400 calls is too expensive). There there is not a desire to change this functionality.

But it may be worthwhile to document this in the function NatSpec for people reading the contract and writing contracts that interact with AreaNFT. Therefore:

This is a valid bug report. Impact rating is somewhere along the line of an-advanced-user-who-has-permission-to-do-something-might-make-a-mistake-because-they-were-expecting-something-that-is-not-reasonable-to-always-expect-but-could-be-improved-with-better-documentation. That is not the final decision on the rating, and we will classify it properly for you. But either way, valid and will result in a change of documentation.

---

# Consolation prizes:

You already won so not sure if this can be called a consolation prize. :-)

- There's two grammatical errors in the 721 spec quoted above. If you like you can be the one to PR that.
- The 721 spec separately includes a related error. In the NatSpec for `onERC721Received` see the note about "`transfer`". There is actually no such thing as "`transfer`" and this should be "`safeTransferFrom`". If you like you can be the one to PR that.

**Comment by markegli** [comment]
That's an amazingly detailed response. Thanks for the careful consideration!

**Comment by fulldecent** [comment]
Thank you for your bug report! We worked on this at https://github.com/AreaWorld/ethereum-contracts/pull/6

Here are some notes on rating your finding.

IMPACT:

As per the notes above, this is somewhere between "affects the development process and validity of the applied code" and "notable". Let's call this "low impact".

LIKELIHOOD:

For this issue to cause the impact above, somebody would need to design a smart contract to perform Area token NFT splits, but then implement that contract so that it depends on the false assumption of having onERC721Received called. 

Because we do not ourselves provide any contracts like the above, nor specifically encourage people to make them, this likelihood is somewhere below "a scenario that actually happens naturally in production deployments". Let's call this "low likelihood".

PAYOUT:

According to the bug bounty rules, this is an accepted problem with a risk rating of "notable". You win:

- This limited, first edition Area T-shirt, mailed to your house, in time for you to wear at NFT.nyc
- One Area NFT token from the token drop
- Public acknowledgement from the Area team and personally from the contract developer on Twitter (if you allow)

Please contact us privately at marcos@area.world or on our Discord to @DappPunk#9999 to arrange these.
